# -*- coding: utf-8 -*-
"""Article to Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPv0eIJv0_vpAj6Q8Pm8F8nz7rVVeklG
"""

!pip install --upgrade diffusers transformers accelerate safetensors

import os, torch
from diffusers import StableDiffusionPipeline

# Output folder
OUT = "/content"
os.makedirs(OUT, exist_ok=True)

# PUBLIC model (never gives 401)
MODEL = "runwayml/stable-diffusion-v1-5"

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

# Load pipeline safely (no xformers, no checker)
pipe = StableDiffusionPipeline.from_pretrained(
    MODEL,
    torch_dtype=dtype,
    safety_checker=None
).to(device)

pipe.enable_attention_slicing()

# Super-clean realistic prompts
prompts = {
  "Article1_img1.png": "Realistic cinematic sunset photo of an African village with solar panels, families walking, children playing, natural skin, sharp details, warm lighting, documentary style, no text",
  "Article1_img2.png": "Wide-angle realistic shot of wind turbines near a coastal village, villagers repairing tools, bright clean lighting, detailed textures, no text",

  "Article2_img1.png": "Realistic photograph of a youth protest, young crowd holding blank signs, natural expressions, clean lighting, street documentary look, no text",
  "Article2_img2.png": "Warm emotional candlelight vigil scene, young people lighting candles, glow on faces, shallow depth of field, clean realistic details, no text",

  "Article3_img1.png": "Modern creative studio with holographic displays, designers working, neon highlights, realistic environment, high quality, no text",
  "Article3_img2.png": "Close-up of computer workstation with bright digital screens, hand pointing at screen, crisp detail, clean reflections, realistic lighting, no text"
}

NEG = "ugly, blurry, low quality, distorted face, bad anatomy, text, watermark, extra limbs"

for i, (name, prompt) in enumerate(prompts.items(), start=1):
    print("Generating:", name)
    seed = 1234 + i
    gen = torch.Generator(device=device).manual_seed(seed)

    img = pipe(
        prompt,
        height=720,
        width=512,
        num_inference_steps=35,
        guidance_scale=8,
        negative_prompt=NEG,
        generator=gen
    ).images[0]

    img.save(os.path.join(OUT, name))
    print("Saved:", name)

print("DONE — Go check /content for 6 images!")